services:
  minio:
    image: quay.io/minio/minio
    container_name: minio
    ports:
      - 9000:9000
      - 9001:9001
    volumes:
      - ./dockerdata/minio:/data
    environment:
      - MINIO_ROOT_USER=admin
      - MINIO_ROOT_PASSWORD=adminadmin
    command: server /data --console-address ":9001"
  backend:
    image: videoshotsbackend
    container_name: backend
    ports:
      - 8000:8000   
    build:
      context: videoshotsBackend
      dockerfile: Dockerfile

  frontend:
    image: videoshotsfrontend
    container_name: frontend
    ports:
      - 4200:4200
    build:
      context: videoshotsFrontend
      dockerfile: Dockerfile
