# Generated by Django 3.2.25 on 2024-07-10 18:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Screenshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('screenshot', models.ImageField(upload_to='pictures/screenshots')),
                ('title', models.CharField(max_length=70)),
                ('description', models.TextField(max_length=300)),
                ('publication_date', models.DateField()),
            ],
        ),
    ]
