# Generated by Django 3.2.25 on 2024-07-28 13:50

from django.db import migrations, models
import django_minio_backend.models


class Migration(migrations.Migration):

    dependencies = [
        ('screenshots', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='screenshot',
            name='screenshot',
            field=models.FileField(storage=django_minio_backend.models.MinioBackend(bucket_name='videoshots'), upload_to=django_minio_backend.models.iso_date_prefix, verbose_name='Bild'),
        ),
    ]
